[unstable]
build-std = ["core", "compiler_builtins"] # This tells cargo that it should recompile the core and compiler_builtins libraries. The latter is required because it is a dependency of core.
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64_custom_target.json"
